### PR TITLE
Remove void in functions parameters

### PR DESCRIPTION
**Pull request by rmaxi-me**
* In C, we use `void` in function parameters to explicitly say the function takes no parameters.  
The following C code compiles :
```c
#include <stdio.h>

// Add void in the parameters and it doesn't compile anymore.
void print_hello()
{
    puts("Hello world");
}

int main()
{
    print_hello(42, 21, "Foo");
}
```
* In C++, the explicit mention of `void` is not necessary because the code will not compile anyways.

**This pull request removes the unnecessary voids in function parameters.**  
I did not touch html, js and tex files.

### CODE REVIEW

**Comment by maastrich** [comment]
This Pull request just remove some explicit informations an seems to be quite useless btw..

**Comment by MatthieuMv** [comment]
Void parameter in c++ function is part of my C++ guideline which focus on being as explicit as possible.

It won't cause any compilation isssue so I won't change it, sorry :/

**Comment by rmaxi-me** [comment]
#### From the official C++ Standard:
> **NL.25: Don’t use void as an argument type**
> **Reason** It’s verbose and only needed where C compatibility matters.
> *Even Dennis Ritchie deemed void f(void) an abomination. You can make an argument for that abomination in C when function prototypes were rare so that banning would have caused major problems, but not in the 21st century and in C++.*

[**Source - isocpp.github.io**](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl25-dont-use-void-as-an-argument-type)

**Comment by Oursin** [comment]
Could we please reopen this pull request ?
It seems quite stubborn to simply close a PR in the name of someone's "own guidelines" that goes directly against the language standard.

**Comment by MatthieuMv** [comment]
What's the point about removing explicit informations ?
That's what make C++ great for designing API in my opinion.

Please find real issues that really need my attention instead of complaining about the most insignificant part of the core guideline  -.-'

**Comment by rmaxi-me** [comment]
### The API is supposed to represent the global level of the students.

Going against the **official C++ standard** is a bad habit. Hundreds, if not thousands, of people agreed to certain rules and good practices by creating a standard for a reason.  

You use the `-pedantic` compilation flag:
> => man gcc
> -pedantic
> Issue all the warnings demanded by strict ISO C and ISO C++; reject all programs that use forbidden extensions, and some other programs that do not follow ISO C and ISO C++.  For ISO C, follows the version of the ISO C standard specified by any -std option used.

If you use this flag, it's because you want your code to follow the standards as much as possible. In openZia, we use the **C++17**, why wouldn't we comply to the current standard instead of the C one? If there is/was a flag as strict as `-pedantic` but for C++17, you would have tons of warnings.

If on a documentation I see `function()` I'm not going to send any parameters. **No one** needs a `function(void)` to understand that.

#### Please quit the 1st year C coding style rule, it does not apply to C++ at all.

**Comment by MatthieuMv** [comment]
Did you just look at the code inside of the repository ?

I doubt you realize how much efforts I've done **alone** to give **you** a complete code base of modern C++17 code, following extremely strict and rigorous rules that aims to give the most of the language.

If you think that I follow C rules just because I prefer to be explicit about function without parameters, you are definitely not understanding anything about C++.

You definitely should try to learn something out of it instead of insulting my work.

**Comment by Oursin** [comment]
> I doubt you realize how much efforts I've done *alone*

That itself is a problem considering that this project should be carried in groups of 4 to 6 students not alone, but anyway.

> modern C++17 code, following extremely strict and rigorous rules

Except for this problem which is against every C++ standard. and the 10 other errors reported by [cppcheck](http://cppcheck.sourceforge.net/). We are not trying to insult your work, but simply to improve it's quality on one of it's few weak points.

And by the way, don't take this that much to heart, it is simply a 2 month long project, it's no big deal :smile:

**Comment by Ph4ntomas** [comment]
I suggest everyone here stop posting in this PR.

While you might have you're view of what one should do or not in C++, you're just nitpicking on something that is valid, as defined by the same standard you're just citing, which state that the naming convention and layout guideline are there to be used for consistency, if you do not have constraint or a better idea.

While you might argue that matthieu's idea is not "better", none of you have actually given any reason about why it would be so. You've just cherrypicked some part of the standard, without even taking into account the introduction of the section you're all relying on to criticize it's work.

If this kind of calling convention don't suit you, I'd suggest to follow your own advice and stop "taking this that much to heart". I'd also suggest to stop doing this kind of meaningless PR, as that only waste everyone time.

I'd like to kindly remind all of you that this is still a school project, at least until the defense, and that I won't hesitate to apply sanction to anyone thinking it's a good idea to do useless troll on this repository.

**Pull request closed without merging**
