### PR TITLE
fix: include winsock2 | refactor: inline keyword

### PR DESCRIPTION
**Pull request by Mathieu-Lala**
fix: include winsock2 to avoid multiple include

refactor: add inline keyword for function definition in header included multiple times

### CODE REVIEW

**Comment by jeremylvln** [comment]
Why do you include winsock2? It's not required to work and you shouldn't include a header you don't use further.

**Comment by Mathieu-Lala** [comment]
Windows.h will include winsock.h, and i want to include winsock2.h somewhere else, so i will have macro/function redefinition. To avoid that, just include winsock2.h before windows.h.

**Comment by jeremylvln** [comment]
lgtm :)

**Comment by MatthieuMv** [comment]
I understand the need of this pull request but I must disagree with every function being inlined.

According to Bjarne Stroustrup in his book "A tour of C++":

"Functions defined in a class are inlined by default. It is possible to explicitly request inlining by preceding a function declaration with the keyword inline ."

Thus, I prefer let the compiler choose which functions will be inlined and when really needed, explicitly tell the compiler to inline it.

For the winsock2 I don't like this alternative as it forces everybody to include it

I see two options:
1- Include winsock before each header (frustrating for you, I have to admit)
2- Add a macro check like OPENZIA_USE_WINSOCK2 in OperatingSystem or something like OPENZIA_OS_WINDOWS_INCLUDES where you put all needed includes in your needed order

If you find a better way please let me know, for now please create a pull request that only match that winsock2 request and I'll accept it :)

**Comment by MatthieuMv** [comment]
Please check the COMPILATION.md file, I added a OPENZIA_PRE_WINDOWS_INCLUDE macro check that allows you to import **winsock2.h** before any **Windows.h**.

**Pull request closed without merging**
