### PR TITLE
Add context-level temporary storage

### PR DESCRIPTION
**Pull request by jeremylvln**
Some implementers way want to transmit some data across modules or between the server and modules. We can now achieve this thanks to a raw metadata map which binds a `string` and a value of any type (thanks to `std::any`).

One example: use the same variable containing the root path of the files to serve across the CGI, and Raw File modules.

Another example: use a global configuration file rather than one per module (or override support).

### CODE REVIEW

**Comment by MatthieuMv** [comment]
First I have to say that this is a very clean PR so thank you for that.

Secondly, before merging I'd like to discuss a bit about it.

The first issue that I see is with your first example; If you need a global root path for example, adding it to a metadata table in the Context will force you to **re-create a new instance** of the table for **each packet** before processing it in the pipeline.

The second is that it obfuscate dependencies between modules; If a module need information loaded in another, it can keep a reference of it thanks to **oZ::IModule::getDependencies** and **oZ::IModule::onRetreiveDependencies** and throw if a dependency is missing.

The fact is, if you create your own custom pipeline feeding and depending upon a metadata table, your modules will have a lot of troubles to be exported in other server implementations.

To keep things optimal for cross-server compatibility, I wouldn't add such feature.
However, if you can justify its need over explicit module dependencies, I'll merge it for you ;)

PS: Global config can be great but not for this project as the key here is to create an interface that gives the best cross compatibility between modules (in my opinion). If you want to share a module and you wrote everything in a global configuration file, it can become really tricky :/

**Comment by jeremylvln** [comment]
I understand your point of view, but using this metadata system permits to avoid redundancy between several configurations.

I've a global configuration file like this:

```
CPP_zia_2019 $ cat config.toml
[server]
http_port = 8080
https_port = 8443

[filesystem]
root = "www"
```

To keep cross-compatibility, each module has this root path, as for my __Directory Listing__ module:

```
CPP_zia_2019 $ cat config/ls.toml
root = "www"
```

But, I like the fact that I can have a global configuration which can impact several modules (if present). That's why I don't enforce the presence of the metadata but rather check if it exists and use this value rather then the one inside the configuration of the module.

And yeah, this metadata system don't target talking between modules, it was a mistake to argue with that.

I agree with you that the use cases are not numerous. But it is also the goal to let the developers do smart things with open tools like this one.

Thanks.

**Comment by jeremylvln** [comment]
Maybe I should rather store a shared_ptr to this map and add const getters...

Your thoughts?

**Comment by MatthieuMv** [comment]
Ok I understand your approach and I really like the shared_ptr idea !

Please update your PR and I'll merge it

**Comment by jeremylvln** [comment]
After talking with some persons of the pedagogical team, it seems that using a shared_ptr is not a great idea. We have to deal with shared mutexes and it can be really heavy at runtime especially if you have a lot of client processing in a lot of threads.

Can we just go with a basic `std::unsorted_map`? I don't think that so much data will be stored inside it. Unfortunately, we don't really have the time to add more complex features :/

Thanks.

**Comment by MatthieuMv** [comment]
Shared ptr reference count is thread safe, however, the access of the variable isn't.
If you plan to only use read access, mutexes aren't required.
If you need write it from modules, copying may be a better solution than locking.

Another alternative would be to create a pool of shared ptrs that are only in one context at a time, so you don't need to reallocate everything for each message and you gain ownership so you can modify it with ease.

**Comment by jeremylvln** [comment]
We can't predict that the usage of this metadata system will be clear for everyone, unfortunately. I think we can go as-it. Are you ok with that?

**Comment by MatthieuMv** [comment]
That's good for me !

**Comment by MatthieuMv** [comment]
Hello @IamBlueSlime,

I updated the API and I found a very good way of using your metadata table.

For openSSL we need a custom pointer to SSL structure which was embarrassing as it would requires to add extra thread synchronization into its module.

Now, with metadata, we can pass any client-specific data in addition of its fd and its endpoint.
The idea behind that is to reuse the oZ::Context and store it only once for every client.

This way, we don't over copy contexts and we can reuse memory cached memory of vectors / strings / maps / ... in the context for future usage.

Please check MODULE.md and CONTEXT.md.

Anyway, thank you for your help, I really appreciate your participation !

**Pull request merged**
