### PR TITLE
Add SYSTEM_DARWIN condition for the entrypoint

### PR DESCRIPTION
**Pull request by jeremylvln**
Explicit :)

### CODE REVIEW

**Comment by jeremylvln** [comment]
@MatthieuMv, could you please take a look asap?

**Comment by MatthieuMv** [comment]
Why did you closed your pull request ? It was all good, I was just really busy these past days.

Is it because macos behaves correctly with the SYSTEM_LINUX in entrypoint ? Or had any other reason ?

**Comment by jeremylvln** [comment]
GitHub automatically closes this PR because i've deleted my branch on my fork. Sorry about that.

**Comment by MatthieuMv** [comment]
No problems !

**Pull request closed without merging**
